"""HTTP status code enum for Lambda response handling."""

from enum import IntEnum


class HttpStatusCode(IntEnum):
    """HTTP status codes used across Lambda response building."""

    RESPONSE_OK_CODE = 200
    RESPONSE_CREATED_CODE = 201
    RESPONSE_BAD_REQUEST_CODE = 400
    RESPONSE_UNAUTHORIZED = 401
    RESPONSE_FORBIDDEN_CODE = 403
    RESPONSE_RESOURCE_NOT_FOUND_CODE = 404
    RESPONSE_CONFLICT_CODE = 409
    RESPONSE_UNPROCESSABLE_ENTITY = 422
    RESPONSE_LOCKED_CODE = 423
    RESPONSE_INTERNAL_SERVER_ERROR = 500
    RESPONSE_NOT_IMPLEMENTED = 501
    RESPONSE_SERVICE_UNAVAILABLE_CODE = 503
